### ISSUE TITLE
Expat missing

### ISSUE THREAD

**Issue by Roobyx** [makemeunsee/ichimiginikarasu#12]
Hey mate, I am trying to build the project, but it seems there is a package missing. Since I am no haskell guy, going trough the error I've installed expat, hexpat packages with the stack commands in order to install them globally, but with no luck.

I was getting this error on all systems I tried (both windows and fedora), before and after installing the said packages.

```
hexpat          > configure
hexpat          > Configuring hexpat-0.20.13...
hexpat          > Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependency on a foreign
hexpat          > library:
hexpat          > * Missing C library: expat
hexpat          > This problem can usually be solved by installing the system package that
hexpat          > provides this library (you may need the "-dev" version). If the library is
hexpat          > already installed but in a non-standard location then you can use the flags
hexpat          > --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
Progress 1/2
```

Any ideas on how can I progress?
Thanks!

**Comment by makemeunsee** [comment]
Hi, thanks for the interest.

What system are you running? And what libraries have you installed?
I didnt encounter this error, but from the message I'd expect installing `expat-devel` or equivalent would solve it.

cheers

**Comment by Roobyx** [comment]
Hi, 
I've tried installing it on 2 windows machines (**win 10 and 11**) and on a Nobara Linux (just a **Fedora** distro).
On all of them, I've gotten the Haskell stack from: https://docs.haskellstack.org/en/stable/ 
Then after that, I'm cloning the repo and ran **stack build**

That's when I get that error. So far it has happened on all of the machines in the same way.

I did try -dev as the error says, but have not tried -devel, will try now.

P.S. expat-devel worked for the Fedora distro (installed with yum)

**Comment by makemeunsee** [comment]
Great; if you're using WSL or cygwin on Windows (note I havent tried either), it should just be a matter of finding the equivalent to `expat-devel` and installing it through the package manager.

**Comment by Roobyx** [comment]
Hey, 

So while the expat-devel worked, I am now stuck on the second step with xelatex. I am trying to generate the pdf, but the resulted doesn't pass. Im getting:

I am generating the cards (seemingly fine). Not sure if the warnings are problematic.

```
[usr@fedora ichimiginikarasu]$ stack exec ichimiginikarasu-exe -- -f resources/jpn_words_girardi_kelly -j res/JMdict_e -k res/kanjidic2.xml -n mydeck -i ./input_test > test2.tex
"reordered"
"read code points"
"filtered relevant kanjis"
"loaded kanjis"
"read kanjis"
"prepared similarity func"
"prepared radical func"
Warning: Option --without-gui= is deprecated
Warning: Option --file= is deprecated
Warning: Option --export-pdf= is deprecated
"generated tex content"
"prepared voc map"
"prepared freq map"
"prepared compounds map"
[usr@fedora ichimiginikarasu]$ xelatex test2.tex 
```


Then I trying to generate the pdfs with xelatex ./test2.tex, but I get:
 `! LaTeX Error: File `flashcards.cls' not found.`

re-entering the name progresses things further but then I get the following:

```
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
 
Enter file name: test2.tex
(./test2.tex
 
! LaTeX Error: Two \documentclass or \documentstyle commands.
 
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
 
l.3 \documentclass[papera4_portrait,grid]{
                                          flashcards}
? 
```


Full cmd log:
```
[usr@fedora ichimiginikarasu]$ xelatex ./test2.tex
This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test2.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-05-07>
 
! LaTeX Error: File `flashcards.cls' not found.
 
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)
 
Enter file name: test2.tex
(./test2.tex
 
! LaTeX Error: Two \documentclass or \documentstyle commands.
 
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
 
l.3 \documentclass[papera4_portrait,grid]{
                                          flashcards}
? 
```

**Comment by makemeunsee** [comment]
Hi,

`flashcards.cls` can be installed manually but should come from a latex package, provided by your system's package manager.
You should be able to look up which package provides this file and install it.
Cheers
