### ISSUE TITLE
Kanji meaning

### ISSUE THREAD

**Issue by halogenandtoast** [makemeunsee/ichimiginikarasu#5]
You use 一右二烏 which is "one right, two birds" and your transliteration to ichimiginikarasu means "one right, two crows". Did you mean to use 一石二鳥 issekinichou (one stone, two birds)?

**Comment by dagit** [comment]
You are correct and I think the author did it on purpose: https://www.reddit.com/r/LearnJapanese/comments/8jezlt/i_made_free_printable_kanji_flashcards_and_open/dyzen09/

**Comment by halogenandtoast** [comment]
Seems so, fair enough. I thought it might be something like this. Could be worth a brief mention in the readme, but not a big deal.
