### ISSUE TITLE
What are the example kanji levels?

### ISSUE THREAD

**Issue by mainrs** [makemeunsee/ichimiginikarasu#6]
There are levels ranging from 2 - 10, but what do they ressable and why is the first one missing? Or is it the last one?

**Comment by makemeunsee** [comment]
the levels are defined as per https://en.wikipedia.org/wiki/Kanji_Kentei
each 'level' file also indicate which grade (in the Japanese system) it corresponds to, e.g.: https://github.com/makemeunsee/ichimiginikarasu/blob/results/sets/level_8
